name: Node CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@v1.6.0
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - shell: sh
        run: yarn build
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/jest@v1.6.0
        with:
          sht-npm-token: ${{ secrets.SHT_NPM_TOKEN }}

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@v1.6.0
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/prettier@v1.6.0
        with:
          sht-npm-token: ${{ secrets.SHT_NPM_TOKEN }}
